import { LEGAL_OPERATOR, LEGAL_VERSION, type LegalSlug } from "./constants";

const { brand, contactEmail, companyPlaceholder, jurisdictionPlaceholder } =
  LEGAL_OPERATOR;

const DISCLAIMER = `These documents are operational templates for ${brand}. They do not replace advice from qualified counsel. Finalize ${companyPlaceholder}, ${jurisdictionPlaceholder}, and contact details before treating them as binding production terms. Version ${LEGAL_VERSION}.`;

export function getLegalBody(slug: LegalSlug): string[] {
  switch (slug) {
    case "terms":
      return [
        DISCLAIMER,
        `By accessing or using ${brand} (the “Service”), you agree to these Terms of Service (“Terms”). If you do not agree, do not use the Service.`,
        "1. Eligibility. The Service is strictly for adults. You must be at least 18 years old (or the age of majority in your jurisdiction, if higher). By using the Service you represent and warrant that you meet this requirement. We may suspend or terminate access if we believe you are underage or have misrepresented your age.",
        "2. Nature of the Service. The Service provides tools for adult creators and agencies to operate AI companion experiences, including messaging channels such as Telegram. Content may be sexual, erotic, or otherwise adult-oriented between consenting adults.",
        "3. Accounts. You are responsible for credentials, API keys, bot tokens, and activity under your account. Notify us promptly of unauthorized use.",
        "4. Acceptable use. You must comply with the Acceptable Use Policy and Adult Content Notice. Zero tolerance for sexual content involving minors (real or fictional), age-play involving minors, exploitation, non-consensual intimate imagery, or other illegal activity.",
        "5. AI outputs. Outputs are generated by machine-learning systems and may be inaccurate, offensive, or unexpected. You are responsible for reviewing, configuring, and deploying personas and for how end users interact with your bots.",
        "6. End users of your bots. If you connect Telegram or other channels, you must ensure your end users are adults, present required notices, and obtain any consents required by law for adult content in your markets.",
        "7. Intellectual property. You retain rights in content you upload (e.g. persona text, photos you own). You grant us a limited license to host and process that content to operate the Service. Do not upload content you lack rights to use.",
        "8. Suspension. We may suspend or terminate accounts that violate these Terms, applicable law, or platform rules of connected services (e.g. Telegram).",
        "9. Disclaimers. THE SERVICE IS PROVIDED “AS IS” WITHOUT WARRANTIES OF ANY KIND TO THE MAXIMUM EXTENT PERMITTED BY LAW.",
        "10. Limitation of liability. To the maximum extent permitted by law, we are not liable for indirect, incidental, special, consequential, or punitive damages, or loss of profits, data, or goodwill.",
        "11. Changes. We may update these Terms. Material changes will be reflected by a new legal version date. Continued use after the effective date constitutes acceptance where permitted by law.",
        `12. Contact. ${contactEmail}`,
      ];
    case "privacy":
      return [
        DISCLAIMER,
        `This Privacy Policy explains how ${brand} processes personal data when you use the Service.`,
        "1. Data we process. Account identifiers (e.g. email / auth provider id), age and adult-consent attestations and timestamps, persona configuration, chat/memory data you create, Telegram bot tokens and webhook metadata you supply, peer shadow identifiers for messaging isolation, usage metrics, and technical logs.",
        "2. Purposes. Provide and secure the Service; enforce 18+ and safety rules; operate bots and memory; customer support; comply with law; prevent abuse and fraud.",
        "3. Legal bases (where GDPR/UK GDPR apply). Contract performance; legitimate interests (security, abuse prevention, product integrity); consent (adult content access attestation and marketing if any); legal obligation.",
        "4. Sharing. Processors that host infrastructure (e.g. cloud/database), authentication provider, model inference providers you enable, and Telegram when you connect bots. We do not sell personal data.",
        "5. International transfers. Data may be processed in regions where our providers operate. We use appropriate safeguards where required.",
        "6. Retention. Account and persona data while your account is active; peer chat/memory per product settings; logs for a limited security period; deletion upon verified account-deletion requests subject to legal holds.",
        "7. Security. Access controls, secrets management, and transport encryption in transit. No method is 100% secure.",
        "8. Your rights. Depending on jurisdiction: access, correction, deletion, restriction, portability, objection, and withdrawal of consent. Contact the email below. You may also complain to a supervisory authority.",
        "9. Children. The Service is not directed to anyone under 18. We do not knowingly collect data from minors. If you believe a minor has used the Service, contact us for deletion.",
        "10. Cookies. We use a necessary adult-access cookie after you attest you are 18+ and accept required policies. Essential auth cookies from our identity provider may also be set.",
        `11. Contact. ${contactEmail}`,
      ];
    case "acceptable-use":
      return [
        DISCLAIMER,
        `This Acceptable Use Policy (“AUP”) applies to all use of ${brand}.`,
        "You may not use the Service to:",
        "• Create, request, store, or distribute sexual content involving anyone 17 or under — including fictional, roleplay, “aged-up”, or AI-generated depictions of minors.",
        "• Engage in age-play that portrays a participant as under 18.",
        "• Exploit, groom, traffic, or otherwise harm people; or facilitate illegal sexual activity.",
        "• Share non-consensual intimate imagery, deepfake pornography of real people without lawful consent, or doxxing material.",
        "• Impersonate others to defraud, blackmail, or commit crimes.",
        "• Attack, scrape abusively, reverse engineer to bypass safety, or disrupt the Service.",
        "• Violate Telegram, payment, or other third-party platform terms in a way that creates unlawful or abusive outcomes through our Service.",
        "Enforcement. We may remove content, disable bots, suspend accounts, preserve evidence, and report to law enforcement when we believe there is a risk of harm or illegal activity involving minors or other serious crimes.",
        `Report abuse: ${contactEmail}`,
      ];
    case "adult-content":
      return [
        DISCLAIMER,
        `${brand} is an adults-only service. By entering you confirm you are 18+ (or older if required where you live).`,
        "Content may include erotic and sexually explicit material depicting and describing consenting adults. If you are offended by such material, do not enter.",
        "We use self-attestation (checkboxes / Telegram confirmation) as a gate. This is not government ID verification. Stronger age-assurance may be required in some jurisdictions; operators must not enable the Service where local law forbids this model without additional controls.",
        "Creators connecting bots must surface an 18+ notice to end users and must not knowingly allow minors to interact with adult personas.",
        "Zero tolerance for sexual content involving minors. Violations result in termination and may be reported to authorities.",
        `Questions: ${contactEmail}`,
      ];
    default:
      return [DISCLAIMER];
  }
}
